from sqlalchemy.orm import Session
from backend.models import ProductModel, SaleModel, SaleItemModel, MovementModel

INITIAL_SEED_PRODUCTS = [
    {
        "id": "sabc-castel-65",
        "name": "Castel Beer 65cl",
        "brand": "Castel",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 7200,
        "sell_price_bottle": 700,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 36,
        "image_url": "/branding/016e6b54-298e-48f0-b95a-f34c9ce70a96.jpg",
    },
    {
        "id": "sabc-mutzig-65",
        "name": "Mützig 65cl",
        "brand": "Mützig",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 7800,
        "sell_price_bottle": 750,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/5a69667c-f61f-47c6-9dc6-3f3d8874210d.jpg",
    },
    {
        "id": "sabc-33-65",
        "name": '"33" Export 65cl',
        "brand": "33 Export",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 7200,
        "sell_price_bottle": 700,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 36,
        "image_url": "/branding/5c4621e6-a61c-4d98-b220-131933d4d5d2.jpg",
    },
    {
        "id": "sabc-beaufort-lager-65",
        "name": "Beaufort Lager 65cl",
        "brand": "Beaufort",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 7800,
        "sell_price_bottle": 800,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/9f8b15c8-8bf1-47cb-b0ca-c94a1c76b1fb.jpg",
    },
    {
        "id": "gn-stout-65",
        "name": "Guinness Foreign Extra Stout 65cl",
        "brand": "Guinness",
        "supplier": "Guinness Cameroun",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 10200,
        "sell_price_bottle": 1000,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 36,
        "image_url": "/branding/dc90d4c5-87da-430c-858f-e83f8f4c9d31.png",
    },
    {
        "id": "gn-smooth-50",
        "name": "Guinness Smooth 50cl",
        "brand": "Guinness",
        "supplier": "Guinness Cameroun",
        "category": "Bières & Stouts",
        "format": "Bouteille 50cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 9000,
        "sell_price_bottle": 900,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/622b73ab-e877-421d-8181-69ee11755863.png",
    },
    {
        "id": "gn-harp-65",
        "name": "Harp Lager 65cl",
        "brand": "Harp",
        "supplier": "Guinness Cameroun",
        "category": "Bières & Stouts",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 7800,
        "sell_price_bottle": 750,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/69b336fe-98ba-46b2-a96e-6c9cc913bca3.png",
    },
    {
        "id": "sabc-top-orange-65",
        "name": "TOP Orange 65cl",
        "brand": "TOP",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Boissons Gazeuses",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 5400,
        "sell_price_bottle": 500,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/154bd092-3afa-41c7-b92d-1d5ef4a073fb.webp",
    },
    {
        "id": "sabc-djino-65",
        "name": "D'Jino Cocktail 65cl",
        "brand": "D'Jino",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Boissons Gazeuses",
        "format": "Bouteille 65cl",
        "bottles_per_casier": 12,
        "buy_price_casier": 6000,
        "sell_price_bottle": 600,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 24,
        "image_url": "/branding/74e85544-4149-4f47-8cca-591365404a02.jpg",
    },
    {
        "id": "sabc-tangui-15",
        "name": "Source Tangui 1.5L",
        "brand": "Source Tangui",
        "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
        "category": "Eaux Minérales",
        "format": "Pack 6 Bouteilles 1.5L",
        "bottles_per_casier": 6,
        "buy_price_casier": 1800,
        "sell_price_bottle": 400,
        "current_stock_bottles": 0,
        "min_alert_threshold_bottles": 30,
        "image_url": "/branding/3eb82c7c-b948-467f-959c-a52672c53cd1.jpg",
    },
]


def seed_initial_data(db: Session):
    existing_count = db.query(ProductModel).count()
    if existing_count == 0:
        print("[Database Seed] Seeding initial SABC & Guinness product catalog with real images...")
        for item in INITIAL_SEED_PRODUCTS:
            prod = ProductModel(**item)
            db.add(prod)
        db.commit()
        print("[Database Seed] Catalog seeding complete! Zero fake sales generated.")
