from sqlalchemy.orm import Session
from backend.models import ProductModel

INITIAL_SEED_PRODUCTS = [
  // --- SABC BIERES ---
  {
    "id": "sabc-castel-65",
    "name": "Castel Beer 65cl",
    "brand": "Castel",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 7200,
    "sell_price_bottle": 700,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 36,
    "image_url": "/branding/016e6b54-298e-48f0-b95a-f34c9ce70a96.jpg",
  },
  {
    "id": "sabc-mutzig-65",
    "name": "Mützig 65cl",
    "brand": "Mützig",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 7800,
    "sell_price_bottle": 750,
    "current_stock_bottles": 36,
    "stock_glaces": 22,
    "stock_non_glaces": 14,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/5a69667c-f61f-47c6-9dc6-3f3d8874210d.jpg",
  },
  {
    "id": "sabc-33-65",
    "name": '"33" Export 65cl',
    "brand": "33 Export",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 7200,
    "sell_price_bottle": 700,
    "current_stock_bottles": 60,
    "stock_glaces": 36,
    "stock_non_glaces": 24,
    "min_alert_threshold_bottles": 36,
    "image_url": "/branding/5c4621e6-a61c-4d98-b220-131933d4d5d2.jpg",
  },
  {
    "id": "sabc-beaufort-lager-65",
    "name": "Beaufort Lager 65cl",
    "brand": "Beaufort",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 7800,
    "sell_price_bottle": 800,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/9f8b15c8-8bf1-47cb-b0ca-c94a1c76b1fb.jpg",
  },
  {
    "id": "sabc-beaufort-light-33",
    "name": "Beaufort Light 33cl",
    "brand": "Beaufort",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 12000,
    "sell_price_bottle": 600,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/be16e442-f0b2-40a4-8e1f-862ef4665a42.webp",
  },
  {
    "id": "sabc-doppel-65",
    "name": "Doppel Munich 65cl (Brune Forte)",
    "brand": "Doppel Munich",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 8400,
    "sell_price_bottle": 850,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 36,
    "image_url": "/branding/4c6a60d6-71cb-45f9-9e68-bec988d7986a.jpg",
  },
  {
    "id": "sabc-castel-milk-stout-65",
    "name": "Castel Milk Stout 65cl",
    "brand": "Castel",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 8400,
    "sell_price_bottle": 850,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/016e6b54-298e-48f0-b95a-f34c9ce70a96.jpg",
  },
  {
    "id": "sabc-heineken-33",
    "name": "Heineken 33cl",
    "brand": "Heineken",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 16800,
    "sell_price_bottle": 1000,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/60689e5f-9013-4f84-bca8-d5cac8680b32.jpg",
  },
  {
    "id": "sabc-amstel-50",
    "name": "Amstel 50cl",
    "brand": "Amstel",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 12500,
    "sell_price_bottle": 750,
    "current_stock_bottles": 40,
    "stock_glaces": 24,
    "stock_non_glaces": 16,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/fd77f5e3-ff08-457c-ae92-a987e455042f.jpg",
  },
  {
    "id": "sabc-manyan-65",
    "name": "Manyan 65cl",
    "brand": "Manyan",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 6600,
    "sell_price_bottle": 650,
    "current_stock_bottles": 36,
    "stock_glaces": 22,
    "stock_non_glaces": 14,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/manyan.jpg",
  },
  {
    "id": "sabc-chill-citron-50",
    "name": "Chill Citron 50cl",
    "brand": "Chill",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Bières & Stouts",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 11000,
    "sell_price_bottle": 700,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/be16e442-f0b2-40a4-8e1f-862ef4665a42.webp",
  },
  // --- GUINNESS ---
  {
    "id": "gn-stout-65",
    "name": "Guinness Foreign Extra Stout 65cl",
    "brand": "Guinness",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 10200,
    "sell_price_bottle": 1000,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 36,
    "image_url": "/branding/dc90d4c5-87da-430c-858f-e83f8f4c9d31.png",
  },
  {
    "id": "gn-stout-33",
    "name": "Guinness Foreign Extra 33cl (Petite)",
    "brand": "Guinness",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 13200,
    "sell_price_bottle": 700,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/a923e57b-55b6-41ca-9c3a-2fc286496a7c.png",
  },
  {
    "id": "gn-smooth-50",
    "name": "Guinness Smooth 50cl",
    "brand": "Guinness",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 9000,
    "sell_price_bottle": 900,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/622b73ab-e877-421d-8181-69ee11755863.png",
  },
  {
    "id": "gn-orijin-65",
    "name": "Orijin Herbal 65cl",
    "brand": "Orijin",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 8400,
    "sell_price_bottle": 800,
    "current_stock_bottles": 36,
    "stock_glaces": 22,
    "stock_non_glaces": 14,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/ee76098f-1b4e-49fe-9040-c9fc6e0c06d4.png",
  },
  {
    "id": "gn-harp-65",
    "name": "Harp Lager 65cl",
    "brand": "Harp",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 7800,
    "sell_price_bottle": 750,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/69b336fe-98ba-46b2-a96e-6c9cc913bca3.png",
  },
  {
    "id": "gn-smirnoff-ice-33",
    "name": "Smirnoff Ice Black 33cl",
    "brand": "Smirnoff",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 15600,
    "sell_price_bottle": 800,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/7642241d-d9a1-4bb8-a620-eeed83d9f253.png",
  },
  {
    "id": "gn-malta-btl-33",
    "name": "Malta Guinness Bouteille 33cl",
    "brand": "Malta Guinness",
    "supplier": "Guinness Cameroun",
    "category": "Bières & Stouts",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 9600,
    "sell_price_bottle": 500,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/7330e1a3-1da9-437a-91a6-241c195a316c.png",
  },
  // --- GAZEUSES ---
  {
    "id": "sabc-djino-cocktail-65",
    "name": "D'Jino Cocktail de Fruits 65cl",
    "brand": "D'Jino",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 6000,
    "sell_price_bottle": 600,
    "current_stock_bottles": 36,
    "stock_glaces": 22,
    "stock_non_glaces": 14,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/74e85544-4149-4f47-8cca-591365404a02.jpg",
  },
  {
    "id": "sabc-djino-pamplemousse-65",
    "name": "D'Jino Pamplemousse 65cl",
    "brand": "D'Jino",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 6000,
    "sell_price_bottle": 600,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/46c12814-ef53-4cd7-a462-55f037e9d806.webp",
  },
  {
    "id": "sabc-djino-citron-65",
    "name": "D'Jino Citron 65cl",
    "brand": "D'Jino",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 6000,
    "sell_price_bottle": 600,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/74e85544-4149-4f47-8cca-591365404a02.jpg",
  },
  {
    "id": "sabc-coca-50",
    "name": "Coca-Cola Original 50cl",
    "brand": "Coca-Cola",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 9500,
    "sell_price_bottle": 600,
    "current_stock_bottles": 40,
    "stock_glaces": 24,
    "stock_non_glaces": 16,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/coca_cola.jpg",
  },
  {
    "id": "sabc-coca-zero-50",
    "name": "Coca-Cola Sans Sucre 50cl",
    "brand": "Coca-Cola",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 9500,
    "sell_price_bottle": 600,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/coca_cola.jpg",
  },
  {
    "id": "sabc-fanta-orange-50",
    "name": "Fanta Orange 50cl",
    "brand": "Fanta",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 9500,
    "sell_price_bottle": 600,
    "current_stock_bottles": 40,
    "stock_glaces": 24,
    "stock_non_glaces": 16,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/fanta_orange.jpg",
  },
  {
    "id": "sabc-sprite-50",
    "name": "Sprite 50cl",
    "brand": "Sprite",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 9500,
    "sell_price_bottle": 600,
    "current_stock_bottles": 40,
    "stock_glaces": 24,
    "stock_non_glaces": 16,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/sprite.jpg",
  },
  {
    "id": "sabc-top-orange-65",
    "name": "TOP Orange 65cl",
    "brand": "TOP",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 5400,
    "sell_price_bottle": 500,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/154bd092-3afa-41c7-b92d-1d5ef4a073fb.webp",
  },
  {
    "id": "sabc-top-ananas-65",
    "name": "TOP Ananas 65cl",
    "brand": "TOP",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 65cl",
    "bottles_per_casier": 12,
    "buy_price_casier": 5400,
    "sell_price_bottle": 500,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/3b376bdb-c269-4846-ba7d-ee0068c6a484.webp",
  },
  {
    "id": "sabc-schweppes-tonic-33",
    "name": "Schweppes Tonic 33cl",
    "brand": "Schweppes",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 12000,
    "sell_price_bottle": 650,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/74e85544-4149-4f47-8cca-591365404a02.jpg",
  },
  {
    "id": "sabc-orangina-33",
    "name": "Orangina 33cl",
    "brand": "Orangina",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 33cl",
    "bottles_per_casier": 24,
    "buy_price_casier": 13200,
    "sell_price_bottle": 700,
    "current_stock_bottles": 24,
    "stock_glaces": 14,
    "stock_non_glaces": 10,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/fanta_orange.jpg",
  },
  {
    "id": "sabc-vimto-50",
    "name": "Vimto 50cl",
    "brand": "Vimto",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 9500,
    "sell_price_bottle": 600,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/74e85544-4149-4f47-8cca-591365404a02.jpg",
  },
  {
    "id": "sabc-world-cola-50",
    "name": "World Cola 50cl",
    "brand": "World Cola",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Boissons Gazeuses",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 8000,
    "sell_price_bottle": 500,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 12,
    "image_url": "/branding/coca_cola.jpg",
  },
  // --- EAUX ---
  {
    "id": "sabc-tangui-15",
    "name": "Source Tangui 1.5L",
    "brand": "Source Tangui",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Eaux Minérales",
    "format": "Pack 6 Bouteilles 1.5L",
    "bottles_per_casier": 6,
    "buy_price_casier": 1800,
    "sell_price_bottle": 400,
    "current_stock_bottles": 30,
    "stock_glaces": 18,
    "stock_non_glaces": 12,
    "min_alert_threshold_bottles": 30,
    "image_url": "/branding/3eb82c7c-b948-467f-959c-a52672c53cd1.jpg",
  },
  // --- ENERGISANTES ---
  {
    "id": "sabc-xxl-energy-33",
    "name": "XXL Energy Canette 33cl",
    "brand": "XXL Energy",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Énergisantes & Alcools Mix",
    "format": "Carton 24 Canettes",
    "bottles_per_casier": 24,
    "buy_price_casier": 12000,
    "sell_price_bottle": 650,
    "current_stock_bottles": 48,
    "stock_glaces": 30,
    "stock_non_glaces": 18,
    "min_alert_threshold_bottles": 24,
    "image_url": "/branding/7642241d-d9a1-4bb8-a620-eeed83d9f253.png",
  },
  {
    "id": "sabc-booster-cidre-50",
    "name": "Booster Cidre 50cl",
    "brand": "Booster",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Énergisantes & Alcools Mix",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 12000,
    "sell_price_bottle": 750,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/booster_cider.jpg",
  },
  {
    "id": "sabc-booster-gin-50",
    "name": "Booster Gin Tonic 50cl",
    "brand": "Booster",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Énergisantes & Alcools Mix",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 12000,
    "sell_price_bottle": 750,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/booster_cider.jpg",
  },
  {
    "id": "sabc-booster-whisky-50",
    "name": "Booster Whisky Cola 50cl",
    "brand": "Booster",
    "supplier": "Société Anonyme des Brasseries du Cameroun (SABC)",
    "category": "Énergisantes & Alcools Mix",
    "format": "Bouteille 50cl",
    "bottles_per_casier": 20,
    "buy_price_casier": 12000,
    "sell_price_bottle": 750,
    "current_stock_bottles": 20,
    "stock_glaces": 12,
    "stock_non_glaces": 8,
    "min_alert_threshold_bottles": 20,
    "image_url": "/branding/booster_cider.jpg",
  },
]


def seed_initial_data(db: Session):
  existing_count = db.query(ProductModel).count()
  if existing_count == 0:
    print(
        "[Database Seed] Seeding full SABC & Guinness catalog (36 items) into"
        " SQLite DB..."
    )
    for item in INITIAL_SEED_PRODUCTS:
      prod = ProductModel(**item)
      db.add(prod)
    db.commit()
    print("[Database Seed] Catalog seeding complete!")
