// Rich Cameroon-themed scenarios and quizzes for the Mboa Empire board.

export type ChoiceEffect =
  | { kind: 'gain'; amount: number; flavor: string }
  | { kind: 'pay'; amount: number; flavor: string }
  | { kind: 'skip-turn'; flavor: string }
  | { kind: 'goto-jail'; flavor: string }
  | { kind: 'goto-depart'; flavor: string }
  | { kind: 'nothing'; flavor: string };

export interface ChoiceOption {
  id: string;
  label: string;
  description: string;
  effect: ChoiceEffect;
}

export interface ChoiceScenario {
  eyebrow: string;
  title: string;
  message: string;
  options: ChoiceOption[];
}

export interface Quiz {
  eyebrow: string;
  question: string;
  options: string[];
  correctIdx: number;
  reward: number;
  penalty: number;
  explanation?: string;
}

// ─── AÉROPORT INTERNATIONAL (cell 15) ────────────────────────────────────────
export const AEROPORT_SCENARIOS: ChoiceScenario[] = [
  {
    eyebrow: '✈️ Aéroport International',
    title: "Aéroport de Douala — embarquement",
    message: "Les pistes grouillent : Air France, Asky, Camair-Co. Que choisis-tu ?",
    options: [
      { id: 'conges', label: "Partir en congés en Europe", description: "Billet aller-retour, dépaysement assuré.", effect: { kind: 'pay', amount: 220, flavor: "Direction Paris ! Vacances bien méritées. −220 💎" } },
      { id: 'famille', label: "Recevoir un cousin de la diaspora", description: "Il arrive avec des cadeaux et des €uros.", effect: { kind: 'gain', amount: 180, flavor: "Le cousin a ramené des €uros. +180 💎" } },
      { id: 'business', label: "Voyage business à Lagos", description: "Meeting CEMAC, contrats juteux à signer.", effect: { kind: 'gain', amount: 120, flavor: "Contrats signés en Afrique de l'Ouest. +120 💎" } },
      { id: 'manque', label: "Rater ton vol", description: "Bouchons sur l'axe lourd, embarquement fermé.", effect: { kind: 'skip-turn', flavor: "Vol manqué, tu rates ton prochain tour." } },
    ],
  },
  {
    eyebrow: '✈️ Aéroport International',
    title: "Incident sur le parking de l'aéroport",
    message: "En sortant, tu trouves ta voiture rayée. Que fais-tu ?",
    options: [
      { id: 'sabotage', label: "Constater le sabotage", description: "Carrosserie froissée par un inconnu jaloux.", effect: { kind: 'pay', amount: 150, flavor: "Réparations chez le tôlier. −150 💎" } },
      { id: 'assurance', label: "Faire jouer l'assurance", description: "Procédure longue mais remboursée.", effect: { kind: 'gain', amount: 80, flavor: "Assurance remboursée. +80 💎" } },
      { id: 'oublier', label: "Laisser tomber", description: "Tu rentres furieux mais en paix.", effect: { kind: 'nothing', flavor: "Tu prends ton mal en patience." } },
    ],
  },
  {
    eyebrow: '✈️ Aéroport International',
    title: "Surclassement surprise !",
    message: "L'agence a survendu ton vol. On te propose...",
    options: [
      { id: 'first', label: "Accepter la 1ère classe + dédommagement", description: "Champagne et indemnités.", effect: { kind: 'gain', amount: 250, flavor: "Première classe et chèque cadeau ! +250 💎" } },
      { id: 'next', label: "Refuser et prendre le vol du lendemain", description: "Hôtel offert mais tu rates un tour.", effect: { kind: 'skip-turn', flavor: "Nuit d'hôtel, mais tu rates un tour." } },
      { id: 'partir', label: "Annuler et rentrer chez toi", description: "Pas de voyage, pas de stress.", effect: { kind: 'pay', amount: 40, flavor: "Frais d'annulation. −40 💎" } },
    ],
  },
  {
    eyebrow: '✈️ Aéroport International',
    title: "Marché noir des bagages",
    message: "Un porteur t'offre de revendre tes excédents bagages...",
    options: [
      { id: 'deal', label: "Accepter le deal louche", description: "Cash discret mais risqué.", effect: { kind: 'gain', amount: 160, flavor: "Cash en poche, vite parti. +160 💎" } },
      { id: 'douane', label: "Le dénoncer aux douanes", description: "Citoyen modèle.", effect: { kind: 'gain', amount: 60, flavor: "Récompense civique. +60 💎" } },
      { id: 'arrestation', label: "Te faire prendre", description: "Garde à vue express.", effect: { kind: 'goto-jail', flavor: "Direction commissariat..." } },
      { id: 'fuir', label: "Filer à la sortie", description: "Tu n'as rien vu.", effect: { kind: 'nothing', flavor: "Tu fuis le couloir." } },
    ],
  },
  {
    eyebrow: '✈️ Aéroport International',
    title: "Délégation présidentielle",
    message: "Le tarmac est bloqué pour une délégation officielle.",
    options: [
      { id: 'patience', label: "Patienter avec les VIP", description: "Réseau utile dans la salle d'attente.", effect: { kind: 'gain', amount: 130, flavor: "Contact d'un ministre, +130 💎" } },
      { id: 'partir', label: "Annuler ton voyage", description: "Tu rentres en ville.", effect: { kind: 'pay', amount: 50, flavor: "Frais perdus. −50 💎" } },
      { id: 'manif', label: "Râler bruyamment", description: "Tu te fais virer du salon.", effect: { kind: 'skip-turn', flavor: "Sécurité te raccompagne. Tour suivant raté." } },
    ],
  },
];

// ─── PORT AUTONOME DE DOUALA (cell 17) ───────────────────────────────────────
export const PORT_SCENARIOS: ChoiceScenario[] = [
  {
    eyebrow: '🚢 Port Autonome de Douala',
    title: "Au cœur du commerce maritime",
    message: "Le port de Douala est le poumon économique du Cameroun.",
    options: [
      { id: 'voiture', label: "Dédouaner ta voiture importée", description: "Toyota d'occase venue du Japon.", effect: { kind: 'pay', amount: 180, flavor: "Frais de dédouanement payés. −180 💎" } },
      { id: 'cacao', label: "Exporter une cargaison de cacao", description: "L'or brun camerounais.", effect: { kind: 'gain', amount: 240, flavor: "Cargaison vendue à l'export ! +240 💎" } },
      { id: 'poisson', label: "Acheter du poisson frais", description: "Tu revends au marché Mboppi.", effect: { kind: 'gain', amount: 80, flavor: "Bonne marge sur le poisson. +80 💎" } },
      { id: 'controle', label: "Contrôle douanier surprise", description: "Document manquant...", effect: { kind: 'pay', amount: 90, flavor: "Amende douanière. −90 💎" } },
    ],
  },
  {
    eyebrow: '🚢 Port Autonome de Douala',
    title: "Conteneur en attente",
    message: "Ton conteneur dort en zone sous-douane depuis 3 mois.",
    options: [
      { id: 'pot', label: "Glisser un pot-de-vin au transitaire", description: "Accélère la sortie.", effect: { kind: 'pay', amount: 120, flavor: "Conteneur libéré. −120 💎 (mais récup vente)" } },
      { id: 'magasinage', label: "Payer les frais de magasinage", description: "Tarif officiel salé.", effect: { kind: 'pay', amount: 200, flavor: "Frais de magasinage. −200 💎" } },
      { id: 'abandon', label: "Abandonner la marchandise", description: "Vente aux enchères.", effect: { kind: 'pay', amount: 50, flavor: "Tu perds tout sauf les pénalités. −50 💎" } },
    ],
  },
  {
    eyebrow: '🚢 Port Autonome de Douala',
    title: "Pêche illégale repérée",
    message: "Un chalutier étranger viole les eaux camerounaises.",
    options: [
      { id: 'denoncer', label: "Le dénoncer à la marine", description: "Récompense citoyenne.", effect: { kind: 'gain', amount: 150, flavor: "Marine reconnaissante. +150 💎" } },
      { id: 'racket', label: "Lui demander de payer pour le silence", description: "Risqué.", effect: { kind: 'gain', amount: 250, flavor: "Mafia maritime... +250 💎" } },
      { id: 'ignorer', label: "Faire semblant de rien", description: "Lâche mais sûr.", effect: { kind: 'nothing', flavor: "Tu fermes les yeux." } },
    ],
  },
  {
    eyebrow: '🚢 Port Autonome de Douala',
    title: "Grève des dockers",
    message: "Les dockers paralysent le port. Ta marchandise est bloquée.",
    options: [
      { id: 'attendre', label: "Attendre la fin de grève", description: "Patience...", effect: { kind: 'skip-turn', flavor: "Port bloqué, tu attends. Tour raté." } },
      { id: 'casser', label: "Embaucher des briseurs de grève", description: "Méthode forte.", effect: { kind: 'pay', amount: 180, flavor: "Tu déboques par la force. −180 💎" } },
      { id: 'negocier', label: "Négocier directement avec les délégués", description: "Diplomatie.", effect: { kind: 'gain', amount: 60, flavor: "Accord trouvé, ton lot passe. +60 💎" } },
    ],
  },
  {
    eyebrow: '🚢 Port Autonome de Douala',
    title: "Investissement portuaire",
    message: "Le port lance un appel d'offres pour ses nouveaux quais.",
    options: [
      { id: 'investir', label: "Investir dans les quais", description: "Long terme rentable.", effect: { kind: 'pay', amount: 200, flavor: "Investissement engagé. −200 💎 (rendement futur)" } },
      { id: 'partenaire', label: "S'associer à un partenaire chinois", description: "Capital frais.", effect: { kind: 'gain', amount: 180, flavor: "Partenariat signé ! +180 💎" } },
      { id: 'passer', label: "Passer ton tour", description: "Pas ton domaine.", effect: { kind: 'nothing', flavor: "Tu observes le marché." } },
    ],
  },
];

// ─── GARE ROUTIÈRE (cell 16) ─────────────────────────────────────────────────
export const GARE_SCENARIOS: ChoiceScenario[] = [
  {
    eyebrow: '🚌 Gare Routière',
    title: "Voyage interurbain",
    message: "Direction... ?",
    options: [
      { id: 'village', label: "Aller au village", description: "Famille au bled, dépenses en route.", effect: { kind: 'pay', amount: 60, flavor: "Frais de route au village. −60 💎" } },
      { id: 'd-y', label: "Douala ↔ Yaoundé pour business", description: "Trajet rentable.", effect: { kind: 'gain', amount: 100, flavor: "Business conclu en 2 jours. +100 💎" } },
      { id: 'rate', label: "Rater ton bus", description: "Tu attends jusqu'à demain.", effect: { kind: 'skip-turn', flavor: "Bus raté, tu rates ton prochain tour." } },
      { id: 'taxi', label: "Co-charger un taxi-brousse", description: "Risqué mais rapide.", effect: { kind: 'gain', amount: 50, flavor: "Tu arrives à temps pour un deal. +50 💎" } },
    ],
  },
  {
    eyebrow: '🚌 Gare Routière',
    title: "Accident sur l'axe Édéa",
    message: "Le bus a un accident en pleine route.",
    options: [
      { id: 'aider', label: "Aider les blessés", description: "Héros du jour.", effect: { kind: 'gain', amount: 80, flavor: "Reconnaissance des passagers. +80 💎" } },
      { id: 'fuir', label: "Continuer ton chemin", description: "Pas tes affaires.", effect: { kind: 'nothing', flavor: "Tu pars sans regarder." } },
      { id: 'rapatriement', label: "Payer un taxi pour rentrer", description: "Voyage avorté.", effect: { kind: 'pay', amount: 100, flavor: "Tu rentres bredouille. −100 💎" } },
    ],
  },
  {
    eyebrow: '🚌 Gare Routière',
    title: "Pickpocket à la gare",
    message: "On te vole pendant que tu attends.",
    options: [
      { id: 'porte-feuille', label: "Portefeuille volé", description: "Tu n'as rien vu.", effect: { kind: 'pay', amount: 120, flavor: "Portefeuille disparu. −120 💎" } },
      { id: 'rattraper', label: "Courir après le voleur", description: "Action risquée.", effect: { kind: 'gain', amount: 90, flavor: "Tu le rattrapes ! +90 💎" } },
      { id: 'police', label: "Aller à la police", description: "Procédure longue.", effect: { kind: 'skip-turn', flavor: "Dépôt de plainte interminable. Tour raté." } },
    ],
  },
  {
    eyebrow: '🚌 Gare Routière',
    title: "Bus VIP haut de gamme",
    message: "Une nouvelle compagnie propose Wi-Fi et climatisation.",
    options: [
      { id: 'vip', label: "Voyager en VIP", description: "Confort total.", effect: { kind: 'pay', amount: 80, flavor: "Trajet de luxe. −80 💎" } },
      { id: 'recommander', label: "Recommander à tes contacts", description: "Commission d'apporteur.", effect: { kind: 'gain', amount: 120, flavor: "Commission empochée. +120 💎" } },
    ],
  },
];

// ─── PRISON VERDICTS (cell 22) ───────────────────────────────────────────────
// Each verdict is a randomized "judgment" — visite simple OU peine.
export interface PrisonVerdict {
  eyebrow: string;
  title: string;
  message: string;
  skipTurns: number; // 0 = simple visite, 1-3 = peine
  fine: number;      // gemmes à payer (0 si visite)
}

export const PRISON_VERDICTS: PrisonVerdict[] = [
  { eyebrow: '👮 Visite à Kondengui', title: "Visite à un cousin", message: "Tu apportes du beignet-haricot à ton frère détenu. Émotion forte mais aucune peine pour toi.", skipTurns: 0, fine: 30 },
  { eyebrow: '👮 Visite à Kondengui', title: "Tu passes par hasard", message: "Tu passes devant la prison sans t'arrêter. Aucune conséquence.", skipTurns: 0, fine: 0 },
  { eyebrow: '⚖️ Tribunal correctionnel', title: "Accusé d'évasion fiscale", message: "Un contrôle a révélé des irrégularités. Le juge te condamne à 1 tour de détention provisoire + amende.", skipTurns: 1, fine: 80 },
  { eyebrow: '⚖️ Tribunal correctionnel', title: "Affaire de corruption mineure", message: "Tu as été surpris en train de glisser un billet. 2 tours fermes + amende.", skipTurns: 2, fine: 150 },
  { eyebrow: "⚖️ Cour d'Appel", title: "Détournement de fonds publics", message: "L'affaire est lourde. 3 tours d'incarcération et grosse amende.", skipTurns: 3, fine: 250 },
  { eyebrow: '⚖️ Tribunal', title: "Diffamation sur Facebook", message: "Tu as insulté un notable en ligne. 1 tour en cellule + dédommagement.", skipTurns: 1, fine: 100 },
  { eyebrow: '⚖️ Tribunal', title: "Conduite en état d'ivresse", message: "Contrôle de police, alcootest positif. 1 tour de cuvée et amende.", skipTurns: 1, fine: 60 },
  { eyebrow: '👮 Visite à Kondengui', title: "Soutien moral", message: "Tu apportes ton soutien à un défenseur des droits humains. Ton tour continue.", skipTurns: 0, fine: 0 },
  { eyebrow: '⚖️ Tribunal', title: "Trouble à l'ordre public", message: "Tu as participé à une manif non autorisée. Garde à vue + amende.", skipTurns: 1, fine: 50 },
  { eyebrow: "⚖️ Cour d'Assises", title: "Affaire foncière complexe", message: "Litige avec un voisin, le juge tranche en ta défaveur. 2 tours d'instruction.", skipTurns: 2, fine: 180 },
];

// Kept for backward compatibility — unused but exported
export const PRISON_SCENARIOS: ChoiceScenario[] = [];

// ─── PLACE DES FÊTES (cell 2) ────────────────────────────────────────────────
export const PLACE_FETES_SCENARIOS: ChoiceScenario[] = [
  {
    eyebrow: '🎉 Place des Fêtes',
    title: "Grande fête au quartier !",
    message: 'Bikutsi, Makossa, Saka... Tu es invité.',
    options: [
      { id: 'organise', label: "Financer la fête (notable)", description: "Réputation +, portefeuille −.", effect: { kind: 'pay', amount: 130, flavor: "Tu es l'âme de la soirée. −130 💎" } },
      { id: 'danse', label: "Danser jusqu'à l'aube", description: "Tu rates ton prochain tour.", effect: { kind: 'skip-turn', flavor: "Trop de Bikutsi... tu dors demain." } },
      { id: 'business', label: "Réseauter avec les notables", description: "Bons contacts gagnés.", effect: { kind: 'gain', amount: 110, flavor: "Carnet d'adresses rempli ! +110 💎" } },
      { id: 'partir', label: "Rentrer tôt", description: "Sage, mais ennuyeux.", effect: { kind: 'nothing', flavor: "Tu dors paisiblement." } },
    ],
  },
  {
    eyebrow: '🎉 Place des Fêtes',
    title: "Concert de Charlotte Dipanda",
    message: "L'artiste joue gratuitement pour le quartier.",
    options: [
      { id: 'vip', label: "Pass VIP backstage", description: "Tu rencontres l'équipe.", effect: { kind: 'pay', amount: 90, flavor: "Photos et autographes. −90 💎" } },
      { id: 'vendre', label: "Vendre du jus de bissap", description: "Petite affaire de soirée.", effect: { kind: 'gain', amount: 70, flavor: "Stock épuisé ! +70 💎" } },
      { id: 'merch', label: "Distribuer des flyers de ton biz", description: "Pub directe.", effect: { kind: 'gain', amount: 50, flavor: "Nouveaux clients. +50 💎" } },
    ],
  },
  {
    eyebrow: '🎉 Place des Fêtes',
    title: "Mariage traditionnel bamiléké",
    message: "Tu es invité comme témoin.",
    options: [
      { id: 'dot', label: "Contribuer à la dot", description: "Obligation familiale.", effect: { kind: 'pay', amount: 200, flavor: "Dot remise au beau-père. −200 💎" } },
      { id: 'cadeau', label: "Apporter un cadeau symbolique", description: "Geste suffisant.", effect: { kind: 'pay', amount: 60, flavor: "Cadeau accepté. −60 💎" } },
      { id: 'animer', label: "Animer la cérémonie comme MC", description: "Tu es payé pour ça.", effect: { kind: 'gain', amount: 150, flavor: "MC du jour ! +150 💎" } },
    ],
  },
  {
    eyebrow: '🎉 Place des Fêtes',
    title: "Bagarre à la sortie",
    message: "Deux groupes se chauffent après la fête.",
    options: [
      { id: 'calmer', label: "Calmer la situation", description: "Tu joues le médiateur.", effect: { kind: 'gain', amount: 70, flavor: "Les notables te remercient. +70 💎" } },
      { id: 'temoin', label: "Filmer pour la police", description: "Témoin clé.", effect: { kind: 'gain', amount: 100, flavor: "Tribunal te dédommage. +100 💎" } },
      { id: 'impliquer', label: "Te mêler à la bagarre", description: "Mauvaise idée.", effect: { kind: 'goto-jail', flavor: "Direction commissariat..." } },
    ],
  },
  {
    eyebrow: '🎉 Place des Fêtes',
    title: "Tombola de quartier",
    message: "Le comité organise une tombola.",
    options: [
      { id: 'gros', label: "Acheter beaucoup de tickets", description: "Tente le jackpot.", effect: { kind: 'gain', amount: 220, flavor: "Tu gagnes le 1er lot ! +220 💎" } },
      { id: 'un', label: "Un seul ticket", description: "Modeste participation.", effect: { kind: 'pay', amount: 20, flavor: "Lot de consolation négligeable. −20 💎" } },
      { id: 'aucun', label: "Refuser de participer", description: "Tu n'y crois pas.", effect: { kind: 'nothing', flavor: "Tu observes les autres." } },
    ],
  },
];

// ─── TRÉSOR (cells 10 & 26) ──────────────────────────────────────────────────
export const TRESOR_SCENARIOS: ChoiceScenario[] = [
  {
    eyebrow: '💎 Trésor de la Sanaga',
    title: "Coffre mystérieux retrouvé !",
    message: "Que choisis-tu d'en faire ?",
    options: [
      { id: 'partager', label: "Le partager avec la communauté", description: "Karma + et petit gain.", effect: { kind: 'gain', amount: 80, flavor: "Le quartier te bénit. +80 💎" } },
      { id: 'garder', label: "Tout garder pour toi", description: "Plus risqué, plus payant.", effect: { kind: 'gain', amount: 200, flavor: "Le coffre était plein ! +200 💎" } },
      { id: 'enquete', label: "Le déclarer aux autorités", description: "Honnête mais coûteux.", effect: { kind: 'pay', amount: 50, flavor: "Tu paies la procédure. −50 💎" } },
    ],
  },
  {
    eyebrow: '💎 Trésor caché',
    title: "Vieux billets dans le grenier",
    message: "Tu retrouves la cachette de ton grand-père.",
    options: [
      { id: 'echange', label: "Les échanger à la banque", description: "Procédure officielle.", effect: { kind: 'gain', amount: 150, flavor: "Échange validé. +150 💎" } },
      { id: 'collectionneur', label: "Vendre à un collectionneur", description: "Valeur antique.", effect: { kind: 'gain', amount: 230, flavor: "Collectionneur passionné. +230 💎" } },
      { id: 'jeter', label: "Les jeter", description: "Tu ne sais pas leur valeur.", effect: { kind: 'nothing', flavor: "Tu rates l'occasion." } },
    ],
  },
  {
    eyebrow: '💎 Trésor inattendu',
    title: "Pépite d'or à l'Est",
    message: "On t'offre une pépite trouvée à Bétaré-Oya.",
    options: [
      { id: 'cash', label: "Revendre à un orfèvre", description: "Cash immédiat.", effect: { kind: 'gain', amount: 180, flavor: "Cash empoché. +180 💎" } },
      { id: 'garder', label: "La garder pour la famille", description: "Symbolique.", effect: { kind: 'nothing', flavor: "Héritage gardé." } },
      { id: 'taxer', label: "La déclarer (mines)", description: "Taxes salées.", effect: { kind: 'pay', amount: 70, flavor: "Taxes payées. −70 💎" } },
    ],
  },
  {
    eyebrow: '💎 Trésor',
    title: "Héritage d'une grand-tante",
    message: "Notaire t'appelle, héritage à débloquer.",
    options: [
      { id: 'accept', label: "Accepter l'héritage", description: "Frais notariaux.", effect: { kind: 'gain', amount: 160, flavor: "Héritage versé. +160 💎" } },
      { id: 'partager', label: "Le partager avec la fratrie", description: "Famille unie.", effect: { kind: 'gain', amount: 70, flavor: "Part équitable. +70 💎" } },
      { id: 'refuser', label: "Refuser (dettes cachées)", description: "Méfiance prudente.", effect: { kind: 'nothing', flavor: "Tu passes ton tour de bénéficiaire." } },
    ],
  },
];

// ─── QUIZZES — STADE (Lions Indomptables) ────────────────────────────────────
export const STADE_QUIZZES: Quiz[] = [
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question:
      "En quelle année les Lions ont-ils atteint les quarts du Mondial pour la 1ère fois ?",
    options: ['1982', '1990', '1994', '2002'],
    correctIdx: 1,
    reward: 150,
    penalty: 80,
    explanation: "Italie 1990 — Roger Milla et le coup de tonnerre africain.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Combien de Coupes d'Afrique le Cameroun a-t-il remportées ?",
    options: ['3', '4', '5', '7'],
    correctIdx: 2,
    reward: 150,
    penalty: 80,
    explanation: "5 fois (1984, 1988, 2000, 2002, 2017).",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Qui était capitaine au Mondial 1990 ?",
    options: ['Roger Milla', 'Stephen Tataw', "Samuel Eto'o", 'Patrick Mboma'],
    correctIdx: 1,
    reward: 200,
    penalty: 100,
    explanation: "Stephen Tataw, le capitaine historique.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Qui a marqué le but mythique contre l'Argentine en 1990 ?",
    options: [
      'Roger Milla',
      'François Omam-Biyik',
      'Cyrille Makanaky',
      'Eugène Ekéké',
    ],
    correctIdx: 1,
    reward: 180,
    penalty: 90,
    explanation: "Omam-Biyik, tête plongeante face à Maradona's team.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Année du 1er Ballon d'Or africain de Samuel Eto'o ?",
    options: ['2003', '2004', '2005', '2007'],
    correctIdx: 2,
    reward: 150,
    penalty: 80,
    explanation: "2003, 2004, 2005 — il a gagné 3 fois de suite !",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Médaille d'or olympique des Lions à Sydney en quelle année ?",
    options: ['1996', '2000', '2004', '2008'],
    correctIdx: 1,
    reward: 160,
    penalty: 80,
    explanation: "Sydney 2000, génération dorée.",
  },
];

// ─── QUIZZES — CHANCE (Histoire/Culture du Cameroun) ─────────────────────────
export const CHANCE_QUIZZES: Quiz[] = [
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "En quelle année le Cameroun a obtenu son indépendance ?",
    options: ['1958', '1960', '1961', '1963'],
    correctIdx: 1,
    reward: 120,
    penalty: 60,
    explanation: "1er janvier 1960 — Cameroun français.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Combien de régions administratives compte le Cameroun ?",
    options: ['8', '10', '12', '14'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "10 régions depuis 2008.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Capitale politique du Cameroun ?",
    options: ['Douala', 'Yaoundé', 'Garoua', 'Bafoussam'],
    correctIdx: 1,
    reward: 80,
    penalty: 40,
    explanation: "Yaoundé est la capitale politique ; Douala l'économique.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Premier président du Cameroun ?",
    options: [
      'Paul Biya',
      'Ahmadou Ahidjo',
      'John Ngu Foncha',
      'Solomon Tandeng Muna',
    ],
    correctIdx: 1,
    reward: 120,
    penalty: 60,
    explanation: "Ahmadou Ahidjo (1960–1982).",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Hauteur approximative du Mont Cameroun ?",
    options: ['2 500 m', '3 200 m', '4 095 m', '5 100 m'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "4 095 m — le plus haut sommet d'Afrique de l'Ouest.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Plat le plus emblématique du Cameroun ?",
    options: ['Ndolè', 'Foufou', 'Eru', 'Bobolo'],
    correctIdx: 0,
    reward: 100,
    penalty: 50,
    explanation: "Le Ndolè, plat national avec crevettes ou viande.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Combien de langues officielles a le Cameroun ?",
    options: ['1', '2', '3', '4'],
    correctIdx: 1,
    reward: 80,
    penalty: 40,
    explanation: "Français et Anglais.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Fleuve qui forme l'estuaire de Douala ?",
    options: ['Sanaga', 'Wouri', 'Logone', 'Bénoué'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "Le Wouri.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Combien d'étoiles porte le drapeau camerounais ?",
    options: ['Une', 'Deux', 'Trois', 'Aucune'],
    correctIdx: 0,
    reward: 80,
    penalty: 40,
    explanation: "Une étoile dorée centrée sur la bande rouge.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Quelle est la monnaie du Cameroun ?",
    options: ['Naira', 'CFA (BEAC)', 'Cedi', 'Dollar zonal'],
    correctIdx: 1,
    reward: 80,
    penalty: 40,
    explanation: "Franc CFA d'Afrique Centrale (BEAC).",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Où se trouve le siège de la BEAC ?",
    options: ['Douala', 'Libreville', 'Yaoundé', "N'Djamena"],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Le siège de la BEAC est à Yaoundé.",
  },
  {
    eyebrow: '🇨🇲 Quiz Cameroun',
    question: "Quel artiste a popularisé le Makossa à l'international ?",
    options: ['Manu Dibango', 'Petit Pays', 'Lapiro de Mbanga', 'Anne-Marie Nzié'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Manu Dibango avec « Soul Makossa » (1972).",
  },
];

// ─── QUIZZES — CITÉ UNIVERSITAIRE (cell 24) — universités camerounaises ──────
export const CITE_U_QUIZZES: Quiz[] = [
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle est la 1ère université créée au Cameroun ?",
    options: [
      "Université de Yaoundé (1962)",
      "Université de Douala",
      "Université de Buea",
      "Université de Dschang",
    ],
    correctIdx: 0,
    reward: 140,
    penalty: 70,
    explanation: "Université Fédérale du Cameroun, devenue Université de Yaoundé I.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle université est spécialisée en agronomie ?",
    options: [
      "Université de Yaoundé I",
      "Université de Dschang",
      "Université de Douala",
      "Université de Ngaoundéré",
    ],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Dschang est le pôle agronomique historique.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle université forme principalement aux sciences industrielles et agroalimentaires ?",
    options: [
      "Université de Bamenda",
      "Université de Ngaoundéré (ENSAI)",
      "Université de Maroua",
      "Université de Yaoundé II",
    ],
    correctIdx: 1,
    reward: 140,
    penalty: 70,
    explanation: "Ngaoundéré héberge l'ENSAI (agro-industries).",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle université est anglophone à Buea ?",
    options: [
      "University of Buea",
      "University of Bamenda",
      "University of Yaoundé I",
      "Catholic University",
    ],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Université de Buea, créée en 1993.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle grande école forme l'élite administrative du Cameroun ?",
    options: ["ENAM", "ENS", "EAMAU", "IRIC"],
    correctIdx: 0,
    reward: 150,
    penalty: 70,
    explanation: "ENAM — École Nationale d'Administration et de Magistrature.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quel est le plus haut diplôme universitaire au Cameroun ?",
    options: [
      "Licence",
      "Master",
      "Doctorat (PhD)",
      "Agrégation",
    ],
    correctIdx: 2,
    reward: 100,
    penalty: 50,
    explanation: "Doctorat = sommet du LMD ; l'Agrégation est un concours spécifique.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle école forme les enseignants du secondaire ?",
    options: ["ENS", "ENSP", "ENAM", "FASA"],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "ENS — École Normale Supérieure.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle école forme les ingénieurs Polytechniciens à Yaoundé ?",
    options: ["ENSP", "ENSPT", "ESSEC", "IUT"],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "ENSP — École Nationale Supérieure Polytechnique.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle école forme aux relations internationales ?",
    options: [
      "IRIC (Yaoundé II)",
      "ESSEC",
      "ENAM",
      "FASA",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "IRIC — Institut des Relations Internationales du Cameroun.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Combien d'universités d'État compte le Cameroun ?",
    options: ['6', '8', '10', '12'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "8 universités d'État : Yaoundé I & II, Douala, Buea, Dschang, Ngaoundéré, Maroua, Bamenda.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle université se trouve à l'extrême-nord ?",
    options: [
      "Université de Maroua",
      "Université de Garoua",
      "Université de Ngaoundéré",
      "Université de Bertoua",
    ],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Université de Maroua, créée en 2008.",
  },
  {
    eyebrow: '🎓 Quiz Université du Cameroun',
    question: "Quelle est la principale école de commerce publique ?",
    options: ["ESSEC Douala", "HEC Yaoundé", "FASA Dschang", "ENS"],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "ESSEC — École Supérieure des Sciences Économiques et Commerciales, Douala.",
  },
];

// ─── QUIZZES — MARCHÉ (cell 21) — marchés camerounais ────────────────────────
export const MARCHE_QUIZZES: Quiz[] = [
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Quel est le plus grand marché à ciel ouvert de Douala ?",
    options: ['Marché Mboppi', 'Marché Central', 'Marché Sandaga', 'Marché Mokolo'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Mboppi est célèbre pour la friperie et l'électronique.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Quel marché de Yaoundé est le plus connu pour les produits vivriers ?",
    options: ['Mokolo', 'Mvog-Mbi', 'Mfoundi', 'Madagascar'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Mokolo concentre les vivres frais de tout le pays.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Marché du Mfoundi à Yaoundé est connu pour... ?",
    options: ['Le poisson frais', 'L\'électronique', 'Les chaussures de luxe', 'Les voitures'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Mfoundi est le marché du poisson de Yaoundé.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Le marché de Sandaga se trouve dans quelle ville ?",
    options: ['Yaoundé', 'Douala', 'Bafoussam', 'Bamenda'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "Sandaga est en plein centre de Douala.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Quel marché traditionnel se tient à Bafoussam ?",
    options: ["Marché Casablanca", "Marché Akwa", "Marché 'A'", "Marché Briqueterie"],
    correctIdx: 2,
    reward: 120,
    penalty: 60,
    explanation: "Le « Marché A » de Bafoussam, central et historique.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Le marché de la Briqueterie est célèbre dans quelle ville ?",
    options: ['Douala', 'Bamenda', 'Yaoundé', 'Limbé'],
    correctIdx: 2,
    reward: 110,
    penalty: 50,
    explanation: "Briqueterie est un quartier-marché historique de Yaoundé.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Quel marché est célèbre pour le textile et la friperie à Douala ?",
    options: ['Marché des Fleurs', 'Marché Congo', 'Marché Mboppi', 'Marché Bonabéri'],
    correctIdx: 2,
    reward: 100,
    penalty: 50,
    explanation: "Mboppi — paradis des bons plans textile.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Le « marché des fleurs » se trouve à... ?",
    options: ['Yaoundé', 'Douala', 'Limbé', 'Kribi'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Le marché aux fleurs de Yaoundé, près de l'Hôtel de Ville.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Quel marché frontalier est connu pour le commerce avec le Nigeria ?",
    options: ['Limbé', 'Ekok / Mamfé', 'Garoua', 'Kribi'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Ekok / Mamfé — frontière commerciale stratégique.",
  },
  {
    eyebrow: '🛒 Quiz Marchés du Cameroun',
    question: "Que signifie « bayam-sellam » ?",
    options: [
      "Banquier informel",
      "Revendeuse de produits frais",
      "Transporteur",
      "Étudiant en commerce",
    ],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "« Bayam-sellam » = acheteuse/revendeuse qui anime les marchés.",
  },
];

// ─── QUIZZES — URBAIN (cells 1, 19, 20) — boulevards, quartiers, MAETUR ──────
export const URBAIN_QUIZZES: Quiz[] = [
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Le Boulevard de la Liberté traverse quelle ville ?",
    options: ['Yaoundé', 'Douala', 'Bafoussam', 'Garoua'],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Boulevard de la Liberté, artère emblématique de Douala (Akwa).",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Que signifie l'acronyme MAETUR ?",
    options: [
      "Mission d'Aménagement et d'Équipement des Terrains Urbains et Ruraux",
      "Ministère de l'Aménagement du Territoire",
      "Maîtrise des Espaces Touristiques Régionaux",
      "Agence Étatique des Terrains Urbains",
    ],
    correctIdx: 0,
    reward: 150,
    penalty: 70,
    explanation: "MAETUR aménage et viabilise les terrains avant lotissement.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Pour quel service principal s'adresse-t-on à la MAETUR ?",
    options: [
      "Obtenir un terrain viabilisé",
      "Renouveler son passeport",
      "Payer ses impôts",
      "Inscription au permis de conduire",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "La MAETUR vend des terrains viabilisés (eau, voirie, électricité).",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Quel quartier huppé de Yaoundé abrite de nombreuses ambassades ?",
    options: ['Bastos', 'Briqueterie', 'Mvog-Ada', 'Tsinga'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Bastos = quartier diplomatique de Yaoundé.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Le quartier Bonanjo de Douala est connu pour... ?",
    options: [
      "Les affaires et l'administration",
      "La pêche artisanale",
      "L'agriculture",
      "Le tourisme balnéaire",
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Bonanjo abrite ministères, banques et grands sièges.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Quel boulevard relie le centre de Yaoundé à l'aéroport de Nsimalen ?",
    options: [
      "Boulevard du 20 Mai",
      "Avenue Kennedy",
      "Pénétrante Est",
      "Boulevard Maman Doudou",
    ],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "La pénétrante Est conduit vers l'aéroport Nsimalen.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Quel organisme délivre le permis de bâtir au Cameroun ?",
    options: [
      "La Mairie / Communauté urbaine",
      "La MAETUR",
      "Le MINHDU",
      "La SIC",
    ],
    correctIdx: 0,
    reward: 140,
    penalty: 70,
    explanation: "Les communes délivrent le permis de bâtir (avec avis MINHDU).",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Que veut dire SIC dans l'immobilier camerounais ?",
    options: [
      "Société Immobilière du Cameroun",
      "Société d'Investissement Citoyenne",
      "Service Immobilier Central",
      "Société Industrielle Camerounaise",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SIC construit et loue les logements sociaux.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Place Ahmadou Ahidjo se trouve à... ?",
    options: ['Douala', 'Yaoundé', 'Garoua', 'Maroua'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "Au centre de Yaoundé, près du Boulevard du 20 Mai.",
  },
  {
    eyebrow: '🏙️ Quiz Quartiers & Boulevards',
    question: "Le 20 Mai est célébré au Cameroun comme... ?",
    options: [
      "Fête de l'Indépendance",
      "Fête de l'Unité Nationale",
      "Fête de la Jeunesse",
      "Fête du Travail",
    ],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Fête de l'Unité Nationale (référendum de 1972).",
  },
];

// ─── QUIZZES — STADE supplémentaires (compétitions, qualifs, organisations) ──
export const STADE_QUIZZES_EXTRA: Quiz[] = [
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Quelle CAN le Cameroun a-t-il organisée à domicile en 2022 ?",
    options: ['CAN 1972', 'CAN 2022', 'CAN 2017', 'CAN 2019'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Le Cameroun a accueilli la CAN 2021 (jouée début 2022).",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Position des Lions à la CAN 2022 (Cameroun) ?",
    options: ['Vainqueurs', 'Finalistes', '3e place', 'Demi-finalistes'],
    correctIdx: 2,
    reward: 140,
    penalty: 70,
    explanation: "3e place — défaite contre l'Égypte en demi.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Combien de Mondiaux le Cameroun a-t-il disputé jusqu'en 2022 ?",
    options: ['5', '6', '7', '8'],
    correctIdx: 3,
    reward: 150,
    penalty: 70,
    explanation: "8 participations : 1982, 90, 94, 98, 2002, 2010, 2014, 2022.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Année du premier sacre africain des Lions ?",
    options: ['1972', '1980', '1984', '1988'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "CAN 1984 — premier sacre continental.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Quel sélectionneur a guidé les Lions en or à Sydney 2000 ?",
    options: [
      'Jean-Paul Akono',
      'Pierre Lechantre',
      'Antonio de Oliveira',
      'Winfried Schäfer',
    ],
    correctIdx: 0,
    reward: 160,
    penalty: 80,
    explanation: "Jean-Paul Akono — médaille d'or olympique 2000.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Quel Lion a remporté la Coupe des Confédérations 2003 (titre posthume) ?",
    options: [
      "Marc-Vivien Foé (en hommage)",
      "Patrick Mboma",
      "Geremi Njitap",
      "Rigobert Song",
    ],
    correctIdx: 0,
    reward: 170,
    penalty: 80,
    explanation: "Marc-Vivien Foé — décès sur le terrain, finale jouée en son hommage.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Quel stade a été construit pour la CAN 2021–22 à Yaoundé ?",
    options: ['Olembe', 'Ahmadou Ahidjo', 'Japoma', 'Réunifiation'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Stade Paul Biya d'Olembé, 60 000 places.",
  },
  {
    eyebrow: '⚽ Quiz Lions Indomptables',
    question: "Quel stade de Douala a été inauguré pour la CAN 2021–22 ?",
    options: ['Japoma', 'Bepanda', 'Réunification', 'Mbappé Léppé'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Stade de Japoma à Douala — 50 000 places.",
  },
];

// ─── QUIZZES — QUARTIER ADMINISTRATIF (cell 23) ──────────────────────────────
export const ADMIN_QUIZZES: Quiz[] = [
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Combien de ministères compte environ le gouvernement camerounais ?",
    options: ['~15', '~25', '~35', '~50'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "~35 départements ministériels selon les remaniements.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Qui nomme les ministres au Cameroun ?",
    options: [
      "Le Premier Ministre",
      "Le Président de la République",
      "L'Assemblée Nationale",
      "Le Sénat",
    ],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Le PR nomme et démet les ministres par décret.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Le Cameroun est-il un État unitaire ou fédéral ?",
    options: [
      "Fédéral",
      "Unitaire décentralisé",
      "Confédéral",
      "Régional autonome",
    ],
    correctIdx: 1,
    reward: 120,
    penalty: 60,
    explanation: "État unitaire décentralisé (Constitution de 1996, révisée 2008).",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Quel est le rôle principal du Préfet ?",
    options: [
      "Diriger un département",
      "Présider la cour d'appel",
      "Commander la gendarmerie",
      "Gérer les impôts",
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Le Préfet est le représentant de l'État dans le département.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Combien de départements compte le Cameroun ?",
    options: ['46', '58', '64', '72'],
    correctIdx: 1,
    reward: 140,
    penalty: 70,
    explanation: "58 départements répartis dans 10 régions.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Quel ministère gère l'État civil et le territoire ?",
    options: ['MINAT', 'MINFI', 'MINJEC', 'MINESEC'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "MINAT — Ministère de l'Administration Territoriale.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "MINFI désigne le ministère de... ?",
    options: ['Finances', 'Forêts', 'Fonction Publique', 'Famille'],
    correctIdx: 0,
    reward: 100,
    penalty: 50,
    explanation: "MINFI — Ministère des Finances.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Combien d'arrondissements à Yaoundé ?",
    options: ['5', '6', '7', '10'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Yaoundé compte 7 communes d'arrondissement.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Combien d'arrondissements à Douala ?",
    options: ['4', '5', '6', '7'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Douala compte 6 communes d'arrondissement.",
  },
  {
    eyebrow: '🏛️ Quiz Administration camerounaise',
    question: "Qui est à la tête d'une commune ?",
    options: ['Préfet', 'Maire élu', 'Sous-préfet', 'Gouverneur'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "Le Maire est élu par le conseil municipal.",
  },
  // ─── Communes spécifiques du Cameroun ───────────────────────────────────────
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Comment s'appelle l'organe qui regroupe les 6 mairies de Douala ?",
    options: [
      'Communauté Urbaine de Douala (CUD)',
      'Conseil Municipal',
      'District de Douala',
      'Métropole du Wouri',
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "CUD — Communauté Urbaine de Douala, dirigée par un Maire de la ville.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Qui dirige la Communauté Urbaine (Douala / Yaoundé) ?",
    options: [
      "Un Maire de la ville élu",
      "Un Délégué du Gouvernement (avant 2020)",
      "Un Préfet",
      "Tous ci-dessus selon les époques",
    ],
    correctIdx: 3,
    reward: 150,
    penalty: 70,
    explanation: "Avant 2020 : Délégué du Gouvernement. Depuis : Maire de la ville élu.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Bafoussam est le chef-lieu de quelle région ?",
    options: ['Ouest', 'Nord-Ouest', 'Littoral', 'Centre'],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Bafoussam — capitale de la région de l'Ouest.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Ebolowa est le chef-lieu de quelle région ?",
    options: ['Sud', 'Sud-Ouest', 'Centre', 'Est'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Ebolowa — chef-lieu de la région du Sud.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Maroua est le chef-lieu de quelle région ?",
    options: ['Nord', 'Extrême-Nord', 'Adamaoua', 'Est'],
    correctIdx: 1,
    reward: 120,
    penalty: 60,
    explanation: "Maroua — chef-lieu de l'Extrême-Nord.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Bertoua est le chef-lieu de quelle région ?",
    options: ['Est', 'Centre', 'Adamaoua', 'Sud'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Bertoua — chef-lieu de la région de l'Est.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Ngaoundéré est le chef-lieu de quelle région ?",
    options: ['Nord', 'Adamaoua', 'Extrême-Nord', 'Est'],
    correctIdx: 1,
    reward: 120,
    penalty: 60,
    explanation: "Ngaoundéré — chef-lieu de l'Adamaoua.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Bamenda est le chef-lieu de quelle région ?",
    options: ['Sud-Ouest', 'Nord-Ouest', 'Ouest', 'Adamaoua'],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Bamenda — chef-lieu du Nord-Ouest.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Buea est le chef-lieu de quelle région ?",
    options: ['Sud-Ouest', 'Nord-Ouest', 'Sud', 'Littoral'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Buea — chef-lieu du Sud-Ouest, au pied du Mont Cameroun.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Garoua est le chef-lieu de quelle région ?",
    options: ['Nord', 'Adamaoua', 'Extrême-Nord', 'Est'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Garoua — chef-lieu de la région du Nord.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Combien de communes d'arrondissement compose la ville de Yaoundé ?",
    options: ['5', '6', '7', '8'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "7 communes : Yaoundé I à VII.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Quelle commune de Douala couvre Bonabéri / la rive droite du Wouri ?",
    options: ['Douala I', 'Douala III', 'Douala IV', 'Douala V'],
    correctIdx: 2,
    reward: 140,
    penalty: 70,
    explanation: "Douala IV (Bonabéri) sur la rive droite du Wouri.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Quelle commune de Yaoundé abrite le quartier Bastos ?",
    options: ['Yaoundé I', 'Yaoundé II', 'Yaoundé V', 'Yaoundé VII'],
    correctIdx: 0,
    reward: 140,
    penalty: 70,
    explanation: "Bastos est dans Yaoundé I.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Limbé est célèbre pour... ?",
    options: [
      "Son port pétrolier (SONARA) et ses plages",
      "Sa savane sèche",
      "Ses dunes de sable",
      "Ses montagnes enneigées",
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Limbé — Sud-Ouest, raffinerie SONARA, plages de sable noir.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Kribi est célèbre pour... ?",
    options: [
      "Ses chutes de la Lobé qui se jettent dans la mer",
      "Son désert",
      "Sa fôret de palmiers raphia",
      "Sa neige",
    ],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Chutes de la Lobé — uniques en Afrique, se jettent directement dans l'océan.",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Combien de mandats successifs un Maire peut-il accomplir au Cameroun ?",
    options: [
      "1 seul",
      "2",
      "Pas de limite légale stricte",
      "3 maximum",
    ],
    correctIdx: 2,
    reward: 140,
    penalty: 70,
    explanation: "La loi n'impose pas de limite stricte, contrairement à la présidence (avant 2008).",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Que finance principalement la commune ?",
    options: [
      "Voirie locale, état civil, marchés municipaux",
      "Armée",
      "Université d'État",
      "Politique étrangère",
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Compétences communales : voirie, état civil, marchés, écoles primaires...",
  },
  {
    eyebrow: '🏘️ Quiz Communes du Cameroun',
    question: "Quelle taxe est-ce que la commune perçoit directement ?",
    options: [
      "Taxe communale (CFPB, taxe de séjour, etc.)",
      "TVA nationale",
      "Impôt sur les sociétés",
      "Droits de douane",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Centimes Additionnels Communaux (CAC) + taxes locales.",
  },
];

// ─── QUIZZES — PALAIS ROYAL (cell 7) — palais & chefferies du Cameroun ───────
export const PALAIS_QUIZZES: Quiz[] = [
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Le Palais de l'Unité (Étoudi) sert de résidence à qui ?",
    options: [
      "Premier Ministre",
      "Président de la République",
      "Roi du Cameroun",
      "Président de l'Assemblée",
    ],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Palais d'Étoudi = Palais de l'Unité, résidence présidentielle.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Dans quelle ville se trouve le célèbre Palais du Sultan Bamoun ?",
    options: ['Bafoussam', 'Bandjoun', 'Foumban', 'Bamenda'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Foumban — Palais royal Bamoun, musée traditionnel.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Le Palais Royal de Foumban a été fondé vers... ?",
    options: ['XIVe siècle', 'XVIIe siècle', 'XIXe siècle', 'XXe siècle'],
    correctIdx: 1,
    reward: 150,
    penalty: 70,
    explanation: "Dynastie Bamoun fondée vers 1394 ; le palais actuel remonte au XIXe.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Quel roi mythique des Bamoun a inventé son propre alphabet ?",
    options: [
      'Sultan Njoya',
      'Roi Manga Bell',
      'Roi Douala Manga',
      'Roi Mfoundi',
    ],
    correctIdx: 0,
    reward: 170,
    penalty: 80,
    explanation: "Sultan Ibrahim Njoya — créateur du système d'écriture A-ka-u-ku.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Le Palais des Rois Bandjoun est connu pour... ?",
    options: [
      "Son architecture traditionnelle bamiléké",
      "Ses ruines romaines",
      "Sa façade gothique",
      "Son toit en métal",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Architecture en bambou raphia & toits coniques — patrimoine bamiléké.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Le Palais Présidentiel d'Étoudi a été construit dans les années... ?",
    options: ['1960', '1980', '1990', '2000'],
    correctIdx: 1,
    reward: 140,
    penalty: 70,
    explanation: "Construit dans les années 1980 sous Ahmadou Ahidjo / Paul Biya.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Quelle chefferie traditionnelle est inscrite au patrimoine UNESCO ?",
    options: ['Bandjoun', 'Foumban', 'Bafut', 'Bana'],
    correctIdx: 2,
    reward: 160,
    penalty: 80,
    explanation: "Bafut (Nord-Ouest) — chefferie inscrite au patrimoine.",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Comment appelle-t-on le chef traditionnel chez les Bamoun ?",
    options: ['Sultan', 'Fon', 'Lamido', 'Mbombog'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Sultan — chez les Bamoun (Ouest, Foumban).",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Comment appelle-t-on le chef traditionnel chez les Peuls du Nord ?",
    options: ['Sultan', 'Fon', 'Lamido', 'Tchawana'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Lamido — chef traditionnel peul (Adamaoua, Nord).",
  },
  {
    eyebrow: '👑 Quiz Palais du Cameroun',
    question: "Comment appelle-t-on le chef chez les peuples du Nord-Ouest anglophone ?",
    options: ['Sultan', 'Fon', 'Lamido', 'Mfo'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Fon — Bafut, Bali, Mankon, etc.",
  },
];

// ─── QUIZZES — HÔTEL DES AMBASSADEURS (cell 6) — hôtels du Cameroun ──────────
export const HOTEL_QUIZZES: Quiz[] = [
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Quel hôtel emblématique se trouve à Yaoundé et est étoilé 5 ?",
    options: ['Hilton Yaoundé', 'Krystal Palace', 'Ibis Yaoundé', 'Sawa Hôtel'],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Hilton Yaoundé — hôtel 5* historique en plein centre.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Le Sawa Hôtel se trouve à... ?",
    options: ['Yaoundé', 'Douala', 'Limbé', 'Kribi'],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Sawa Hôtel — Akwa, Douala.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Quel hôtel 5* est célèbre à Kribi pour son cadre balnéaire ?",
    options: ['Framissima', 'Hôtel Ilomba', 'Tara Plage', 'Krystal Palace'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Framissima Kribi — vue océan Atlantique.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Le Krystal Palace est situé à... ?",
    options: ['Douala', 'Yaoundé', 'Limbé', 'Bafoussam'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Krystal Palace — Bonapriso, Douala.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Quel hôtel de la place de l'Unité a accueilli des sommets internationaux ?",
    options: ['Mont Fébé', 'Hilton', 'Sofitel', 'Krystal'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Mont Fébé à Yaoundé — sommet OUA en 1996, etc.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Quel hôtel a été construit pour la CAN 2021–22 à Olembé ?",
    options: ['Hôtel Sawa', 'Hôtel Olembé', "Hôtel La Falaise", 'Star Land'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Complexe hôtelier Olembé — proche du stade Paul Biya.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "La chaîne « La Falaise » possède des hôtels à... ?",
    options: [
      "Yaoundé, Douala, Bafoussam",
      "Seulement Douala",
      "Garoua uniquement",
      "Pas au Cameroun",
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Groupe La Falaise présent dans plusieurs grandes villes.",
  },
  {
    eyebrow: '🏨 Quiz Hôtels du Cameroun',
    question: "Quel hôtel n'est PAS un 4-5 étoiles reconnu au Cameroun ?",
    options: ['Hilton Yaoundé', 'Sawa Hôtel', 'Star Inn quartier populaire', 'Krystal Palace'],
    correctIdx: 2,
    reward: 110,
    penalty: 50,
    explanation: "Un petit hôtel de quartier n'est pas classé 4–5*.",
  },
];

// ─── QUIZZES — ROUTE DES PALMIERS (cell 4) — routes & autoroutes ─────────────
export const ROUTE_QUIZZES: Quiz[] = [
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quelle est la 1ère autoroute construite au Cameroun ?",
    options: [
      "Yaoundé – Douala (phase 1)",
      "Douala – Edéa",
      "Yaoundé – Bafoussam",
      "Limbé – Idenau",
    ],
    correctIdx: 0,
    reward: 140,
    penalty: 70,
    explanation: "Autoroute Yaoundé–Douala (phase 1, Yaoundé–Bibodi) inaugurée vers 2018.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "L'axe lourd Douala–Yaoundé porte le surnom de... ?",
    options: ['N1', 'N2', "L'axe lourd", 'A1'],
    correctIdx: 2,
    reward: 110,
    penalty: 50,
    explanation: "« L'axe lourd » est le grand axe routier le plus stratégique.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "La N1 relie Yaoundé à... ?",
    options: ['Douala', 'Garoua / Nord', 'Bafoussam', 'Limbé'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "La N1 file plein nord vers Garoua, Maroua.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quel grand pont relie Douala à Bonabéri ?",
    options: [
      "Pont sur le Wouri",
      "Pont du Mungo",
      "Pont d'Edéa",
      "Pont sur la Sanaga",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Le pont sur le Wouri — désormais doublé d'un 2e pont.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quel péage est célèbre sur l'axe Douala–Yaoundé ?",
    options: [
      "Péage de Tiko",
      "Péage de Boumnyebel",
      "Péage de Garoua",
      "Péage de Limbé",
    ],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Boumnyebel — péage majeur sur l'axe Douala–Yaoundé.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quel ministère gère les routes nationales ?",
    options: ['MINTP', 'MINFI', 'MINHDU', 'MINEDUB'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "MINTP — Ministère des Travaux Publics.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quelle route mène à Kribi depuis Yaoundé ?",
    options: [
      "N3 via Edéa",
      "N7 via Bafia",
      "N10 via Bertoua",
      "N1 via Garoua",
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "N3 — Yaoundé → Edéa → Kribi.",
  },
  {
    eyebrow: '🛣️ Quiz Routes du Cameroun',
    question: "Quel surnom donne-t-on aux taxi-motos urbains ?",
    options: ['Bend-Skin', 'Clando', 'Opep', 'Boyo'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "« Bend-Skin » — moto-taxis très populaires.",
  },
];

// ─── QUIZZES — ÉCOLE DES LEADERS (cell 5) — leadership / institutions ────────
export const ECOLE_LEADERS_QUIZZES: Quiz[] = [
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Le Cameroun a accédé à l'indépendance d'abord du... ?",
    options: ['Royaume-Uni', 'France', 'Allemagne', 'Belgique'],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Le Cameroun français a accédé à l'indépendance en 1960.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Quel ancien président est resté au pouvoir 22 ans (1960-1982) ?",
    options: ['Ahmadou Ahidjo', 'Paul Biya', 'André-Marie Mbida', 'John Foncha'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Ahmadou Ahidjo — 1er président, 1960-1982.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Quel leader a marqué la lutte anti-colonialiste UPC ?",
    options: [
      "Ruben Um Nyobé",
      "Solomon Tandeng Muna",
      "André Mbida",
      "Marigoh Mboua",
    ],
    correctIdx: 0,
    reward: 150,
    penalty: 70,
    explanation: "Ruben Um Nyobé — leader de l'UPC, assassiné en 1958.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Qui était le Premier ministre du Cameroun britannique ?",
    options: [
      "John Ngu Foncha",
      "Solomon Tandeng Muna",
      "Endeley E.M.L.",
      "Tous les trois ont été PM successifs",
    ],
    correctIdx: 3,
    reward: 170,
    penalty: 80,
    explanation: "Endeley puis Foncha puis Muna — successivement PM du Cameroun britannique.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Date du référendum d'unification du Cameroun ?",
    options: ["11 février 1961", "20 mai 1972", "1er octobre 1961", "Tous ci-dessus liés"],
    correctIdx: 0,
    reward: 160,
    penalty: 80,
    explanation: "11 février 1961 — référendum dans le Cameroun britannique.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Date de la réunification (Cameroun fédéral) ?",
    options: [
      "1er janvier 1960",
      "1er octobre 1961",
      "20 mai 1972",
      "11 février 1961",
    ],
    correctIdx: 1,
    reward: 140,
    penalty: 70,
    explanation: "1er octobre 1961 — réunification officielle.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Quelle organisation continentale le Cameroun a-t-il intégrée à l'indépendance ?",
    options: ['OUA (devenue UA)', 'UE', 'BRICS', 'ASEAN'],
    correctIdx: 0,
    reward: 100,
    penalty: 50,
    explanation: "Organisation de l'Unité Africaine (OUA), aujourd'hui Union Africaine.",
  },
  {
    eyebrow: '🎯 Quiz Leadership Cameroun',
    question: "Quel chef d'État camerounais a accueilli le Pape Jean-Paul II ?",
    options: ['Ahidjo', 'Biya', 'Mbida', 'Foncha'],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "Paul Biya a accueilli Jean-Paul II en 1985 et 1995.",
  },
];

// ─── QUIZZES — CENTRE COMMERCIAL (cell 11) — commerce moderne ────────────────
export const COMMERCE_QUIZZES: Quiz[] = [
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Quel groupe possède la chaîne Mahima au Cameroun ?",
    options: ['Groupe Mahima', 'CFAO', 'Bolloré', 'Castel'],
    correctIdx: 0,
    reward: 100,
    penalty: 50,
    explanation: "Groupe Mahima — grandes surfaces et hypermarchés.",
  },
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Quelle enseigne de supermarché française est implantée au Cameroun ?",
    options: ['Carrefour Market', 'Auchan', 'Casino', 'Lidl'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Carrefour Market (sous franchise) à Douala et Yaoundé.",
  },
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Le centre commercial Akwa Palace est dans quelle ville ?",
    options: ['Yaoundé', 'Douala', 'Bafoussam', 'Bamenda'],
    correctIdx: 1,
    reward: 110,
    penalty: 50,
    explanation: "Akwa Palace est un repère de Douala.",
  },
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Quel est le principal port d'entrée des marchandises au Cameroun ?",
    options: ['Limbé', 'Douala', 'Kribi', 'Garoua'],
    correctIdx: 1,
    reward: 100,
    penalty: 50,
    explanation: "Port de Douala — plus grand port d'Afrique centrale.",
  },
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Quelle TVA s'applique au Cameroun pour la majorité des biens ?",
    options: ['10%', '17,5%', '19,25%', '22%'],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "TVA 19,25% (taux standard).",
  },
  {
    eyebrow: '🏬 Quiz Commerce du Cameroun',
    question: "Quel ministère délivre les licences d'importation ?",
    options: ['MINCOMMERCE', 'MINFI', 'MINEPAT', 'MINAT'],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "MINCOMMERCE — Ministère du Commerce.",
  },
];

// ─── QUIZZES — INDUSTRIE (cell 14) — zone industrielle ───────────────────────
export const INDUSTRIE_QUIZZES: Quiz[] = [
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "Quelle est la principale zone industrielle de Douala ?",
    options: ['Bassa', 'Bonabéri', 'Magzi (Zone industrielle)', 'Toutes ci-dessus'],
    correctIdx: 3,
    reward: 140,
    penalty: 70,
    explanation: "Bassa, Bonabéri et la MAGZI sont les pôles industriels de Douala.",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "Que signifie MAGZI ?",
    options: [
      "Mission d'Aménagement et de Gestion des Zones Industrielles",
      "Ministère de l'Industrie",
      "Agence d'Investissement Industriel",
      "Magasin Géant Industriel",
    ],
    correctIdx: 0,
    reward: 150,
    penalty: 70,
    explanation: "MAGZI — agence publique des zones industrielles.",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "Quelle usine est le plus grand site agroalimentaire au Cameroun ?",
    options: ['SOSUCAM', 'CHOCOCAM', 'Brasseries du Cameroun', 'CICAM'],
    correctIdx: 2,
    reward: 120,
    penalty: 60,
    explanation: "Brasseries du Cameroun (groupe Castel) — leader bières/sodas.",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "SOSUCAM produit principalement... ?",
    options: ['Du sucre', 'Du ciment', 'Du chocolat', 'Du coton'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "SOSUCAM — Société Sucrière du Cameroun (Mbandjock).",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "CIMENCAM est l'usine de... ?",
    options: ['Ciment', 'Cigarette', 'Cuir', 'Coton'],
    correctIdx: 0,
    reward: 100,
    penalty: 50,
    explanation: "Cimenteries du Cameroun (groupe Lafarge-Holcim).",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "CICAM est une usine de... ?",
    options: ['Tissus / textiles', 'Cigarettes', 'Chaussures', 'Carrelage'],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "Cotonnière Industrielle du Cameroun — pagnes et tissus.",
  },
  {
    eyebrow: '🏭 Quiz Industrie du Cameroun',
    question: "Quelle est la plus grande raffinerie pétrolière du Cameroun ?",
    options: ['SONARA (Limbé)', 'SCDP', 'TRADEX', 'PERENCO'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SONARA — Société Nationale de Raffinage à Limbé.",
  },
  // ─── Match product → industrie ─────────────────────────────────────────────
  {
    eyebrow: '🍺 Quiz Industrie — Bière',
    question: "Quelle industrie produit la bière « 33 Export » ?",
    options: [
      'Brasseries du Cameroun (SABC)',
      'CHOCOCAM',
      'NESTLÉ Cameroun',
      'UCB (Union Camerounaise des Brasseries)',
    ],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Brasseries du Cameroun (groupe Castel) — 33 Export, Beaufort, Castel.",
  },
  {
    eyebrow: '🍺 Quiz Industrie — Bière',
    question: "Quelle bière est produite par l'UCB (Union Camerounaise de Brasseries) ?",
    options: ['Mützig', 'King Beer / Pelfort', 'Beaufort', "Guinness"],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "UCB produit King Beer et Pelfort, concurrent des SABC.",
  },
  {
    eyebrow: '🥤 Quiz Industrie — Boissons',
    question: "Quelle usine met en bouteille Top, Djino et Coca-Cola au Cameroun ?",
    options: [
      'SOCAVER',
      'Source du Pays',
      'Brasseries du Cameroun (SABC)',
      'CFAO',
    ],
    correctIdx: 2,
    reward: 130,
    penalty: 60,
    explanation: "Les SABC embouteillent Coca-Cola, Top, Djino et autres sodas.",
  },
  {
    eyebrow: '💧 Quiz Industrie — Eau minérale',
    question: "Quelle eau minérale provient de la « Source du Pays » ?",
    options: ["Tangui", "Vittel", "Supermont", "Evian"],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "Tangui — la marque historique de la Source du Pays.",
  },
  {
    eyebrow: '🍫 Quiz Industrie — Chocolat',
    question: "Quelle entreprise produit le chocolat « Mambo » ?",
    options: ['CHOCOCAM', 'NESTLÉ Cameroun', 'SOSUCAM', 'CICAM'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "CHOCOCAM — fabricant historique de Mambo et Tartina.",
  },
  {
    eyebrow: '🍫 Quiz Industrie — Café',
    question: "Quelle industrie produit le café « Arabica Cameroun » sur grande échelle ?",
    options: ['UCCAO', 'NESTLÉ Cameroun', 'CHOCOCAM', 'SODECOTON'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "UCCAO — Union Centrale des Coopératives Agricoles de l'Ouest.",
  },
  {
    eyebrow: '🧵 Quiz Industrie — Coton',
    question: "Quelle société est chargée de la production cotonnière ?",
    options: ['SODECOTON', 'CICAM', 'UCCAO', 'CDC'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SODECOTON — Société de Développement du Coton, basée à Garoua.",
  },
  {
    eyebrow: '🧵 Quiz Industrie — Pagne',
    question: "Quelle usine transforme le coton en pagnes et tissus ?",
    options: ['CICAM', 'SODECOTON', 'NESTLÉ', 'CIMENCAM'],
    correctIdx: 0,
    reward: 120,
    penalty: 60,
    explanation: "CICAM — Cotonnière Industrielle du Cameroun, tissus et pagnes.",
  },
  {
    eyebrow: '🍌 Quiz Industrie — Plantation',
    question: "Quelle société d'État exploite les plantations de banane et palmier ?",
    options: ['CDC', 'SODECOTON', 'SOSUCAM', 'PAMOL'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "CDC — Cameroon Development Corporation, dans le Sud-Ouest.",
  },
  {
    eyebrow: '⛽ Quiz Industrie — Pétrole',
    question: "Quelle société gère les hydrocarbures pour l'État ?",
    options: ['SNH', 'SONARA', 'TRADEX', 'SCDP'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SNH — Société Nationale des Hydrocarbures.",
  },
  {
    eyebrow: '⛽ Quiz Industrie — Distribution carburant',
    question: "Quelle société distribue les carburants TOTAL/TRADEX en stations ?",
    options: ['TRADEX', 'SONARA', 'CDC', 'CIMENCAM'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "TRADEX (Sté nationale de trading et de distribution).",
  },
  {
    eyebrow: '🚬 Quiz Industrie — Tabac',
    question: "Quelle usine produit les cigarettes au Cameroun ?",
    options: ["BAT Cameroon", "SITABAC", "Brasseries", "SOCAVER"],
    correctIdx: 1,
    reward: 130,
    penalty: 60,
    explanation: "SITABAC — Société Industrielle des Tabacs du Cameroun (Yaoundé).",
  },
  {
    eyebrow: '🥖 Quiz Industrie — Farine',
    question: "Quelle minoterie produit la farine de blé au Cameroun ?",
    options: [
      'SCIM (Minoteries du Cameroun)',
      'SOSUCAM',
      'CDC',
      'CIMENCAM',
    ],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SCIM — Société des Minoteries du Cameroun (groupe Somdiaa).",
  },
  {
    eyebrow: '🧱 Quiz Industrie — Ciment',
    question: "Quelle entreprise n'est PAS un cimentier au Cameroun ?",
    options: ['CIMENCAM', 'Dangote Cement', 'CIMAF Cameroun', 'SOSUCAM'],
    correctIdx: 3,
    reward: 130,
    penalty: 60,
    explanation: "SOSUCAM fait du sucre, pas du ciment.",
  },
  {
    eyebrow: '🍬 Quiz Industrie — Sucre',
    question: "Où se trouve la principale usine SOSUCAM ?",
    options: ['Mbandjock', 'Limbé', 'Douala', 'Garoua'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SOSUCAM exploite la canne à Mbandjock-Nkoteng.",
  },
  {
    eyebrow: '🍶 Quiz Industrie — Verre',
    question: "Quelle entreprise fabrique les bouteilles en verre des SABC ?",
    options: ['SOCAVER', 'SOSUCAM', 'CICAM', 'NESTLÉ'],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "SOCAVER — Société Camerounaise de Verrerie (Douala).",
  },
  {
    eyebrow: '🥛 Quiz Industrie — Lait',
    question: "Quelle marque de lait concentré est associée à NESTLÉ Cameroun ?",
    options: ['Nido / Nestlé Lait', 'Tartina', 'Bonjour', 'Yofrais'],
    correctIdx: 0,
    reward: 110,
    penalty: 50,
    explanation: "NIDO — lait en poudre Nestlé, très consommé.",
  },
  {
    eyebrow: '🍝 Quiz Industrie — Pâtes',
    question: "Quelle usine produit les pâtes alimentaires « Pasta » au Cameroun ?",
    options: ["Pasta Industries (groupe TKC)", "CHOCOCAM", "SOSUCAM", "Nestlé"],
    correctIdx: 0,
    reward: 130,
    penalty: 60,
    explanation: "Plusieurs minoteries produisent des pâtes locales.",
  },
  {
    eyebrow: '🏭 Quiz Industrie — Association produit ↔ usine',
    question: "Quelle association est FAUSSE ?",
    options: [
      'Brasseries du Cameroun → bière 33 Export',
      'CICAM → pagnes',
      'CIMENCAM → bière',
      'SOSUCAM → sucre',
    ],
    correctIdx: 2,
    reward: 140,
    penalty: 70,
    explanation: "CIMENCAM produit du ciment, pas de la bière !",
  },
];

// Pick a random scenario / quiz
export function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
